# Generated by Django 2.2.1 on 2019-05-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=40)),
                ('employee_email', models.EmailField(max_length=30)),
                ('employee_pic', models.FileField(upload_to='images/')),
            ],
        ),
    ]
