# Generated by Django 2.2.1 on 2019-05-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_pic',
            field=models.FileField(upload_to='images/%Y/%m/%d'),
        ),
    ]
