# Generated by Django 2.2.1 on 2019-05-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_auto_20190527_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='created',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
