# Generated by Django 2.2.1 on 2019-05-27 10:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_auto_20190527_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 27, 10, 53, 40, 993332, tzinfo=utc), editable=False),
        ),
    ]
