# Generated by Django 2.2.1 on 2019-05-27 10:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_auto_20190527_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='updated',
        ),
        migrations.AlterField(
            model_name='employee',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 27, 10, 55, 7, 496835, tzinfo=utc), editable=False),
        ),
    ]
